title: Classic Online Garage
author: Bryan Philip
email: classicgarage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  For all those having problems with their classic car a new online solution 
  is being developed to ensure that all those looking for parts and mechanics 
  will be assisted directly.

# social links
twitter_username: Hyphlux # DO NOT include the @ character, or else the build will fail!
github_username:  Bryan-Philip # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
